### ISSUE TITLE
Endpoint summaries are pretty hard to read

### ISSUE THREAD

**Issue by laeyon85002** [oqo0/swagger-themes#1]
First of all, thank you very much for the wonderful plugin. However, the endpoint summaries, which briefly describe the endpoints, are unfortunately hard to read or even unreadable in almost every dark theme. Would it be possible to adjust this manually or can it be classified as a bug?

**Comment by oqo0** [comment]
Hello, thank you for reporting the issue.
Check if the problem was fixed in the new `1.3.2` package version.
You will likely need to clear page cache in order to see the changes.

**Comment by laeyon85002** [comment]
Works like a charm, thank you very much. :)
