### ISSUE TITLE
 Remark lists should also use the primary font color.

### ISSUE THREAD

**Issue by laeyon85002** [oqo0/swagger-themes#4]
When using lists in remarks, they unfortunately also appear illegible. Ideally, the normal/primary font color should be used here as well, as it is more readable.

Example:
![image](https://github.com/oqo0/swagger-themes/assets/55277989/746736e6-1363-4b0b-ae62-c2414be325be)

`/// <summary>Test summary</summary>
/// <remarks>
/// Test remarks
/// For exmaple:
/// 1. First example
/// 2. Second example
/// 3. Third example
///
/// More text right here.
/// </remarks>`

![image](https://github.com/oqo0/swagger-themes/assets/55277989/e2a39671-ba1b-44cb-b5b8-202eb7a7c883)

**Comment by oqo0** [comment]
@laeyon85002 Now font color should be applied to remark lists too. 
Please check if the problem was fixed in `1.3.3` package version.

**Comment by laeyon85002** [comment]
Thank you again. 💯
