### ISSUE TITLE
"Enable Try It Out" option

### ISSUE THREAD

**Issue by DiCaver** [oqo0/swagger-themes#5]
Hi!

I installed this package a few days ago in my C# (.NET 7.0), and I noticed that **EnableTryItOutByDefault()** no longer works. Those are a few lines from my Program.cs:

_app.UseSwagger();
app.UseSwaggerThemes(Theme.UniversalDark);
app.UseSwaggerUI(options => options.EnableTryItOutByDefault());_

Is there any known solution for this?

Thanks and best regards! Marko

P.S.
It's my first open issue in GitHub, so I apologise if this is incorrect.

**Comment by oqo0** [comment]
Hello, @DiCaver, Thank you for your report.
I have tried to replicate the issue on .NET 7 using the latest version of the extension, and `EnableTryItOutByDefault()` works as intended. Can you please provide me with some code that demonstrates the issue, preferably including the relevant endpoints and any relevant screenshots?

**Comment by DiCaver** [comment]
Hi,

I wonder if the problem was that I had Swashbuckle.AspNetCore v6.4.0, but after upgrading to v6.7.0, _EnableTryItOutByDefault()_ with your **SwaggerThemes** starts working as expected. I guess there's no issue, just inexperienced developers 🙂

Thank you for your fast response and for trying to help me!
